_target_: src.models.blt_module.BLTEmbedModule

  
embedder: 
  _target_: src.models.components.blt_model.LocalEncoder
  vocab_size: 258
  d_model: 24
  d_output: 384
  num_layers: 1
  num_heads: 8
  cross_attn_nheads: 8
  dropout: 0.1
  max_seq_len: 2048
  max_patch_len: 256
embedder_output_dim: 384

regressor:
  _target_: src.models.components.mlp.SimpleMLP
  input_dim: 384
  hidden_dim: [2048, 2048]
  output_dim: 1

regressor_optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0003
  weight_decay: 0.00001

scheduler: 
  _target_: transformers.get_linear_schedule_with_warmup
  _partial_: true
  num_warmup_steps: 1000
  num_training_steps: ${trainer.max_epochs}

compile: true

embedder_optimizer:
  _target_: torch.optim.AdamW
  _partial_: true 
  lr: 0.00002
  weight_decay: 0.00001

entropy_model:
  _target_: src.models.components.entropy_model.ByteTransformer

entropy_model_checkpoint: /root/autodl-tmp/universal_offline/universal-offline-bbo/logs/entropy_model/runs/2025-01-10_23-44-21_seed42/checkpoints/epoch_epoch=004.ckpt

entropy_threshold: 0.5

data_dir: ${data.data_dir}
task_names: ${data.task_names}
