_target_: src.models.embed_regressor_module.EmbedRegressorModule

embedder:
  _target_: transformers.GPT2Model
  config:
    _target_: transformers.GPT2Config
    n_layer: 6      
    n_embd: 384        
    n_head: 6        
    max_position_embeddings: 512  
    n_inner: 1536
    head_dim: 64
    vocab_size: 50257
embedder_output_dim: 384

regressor:
  _target_: src.models.components.mlp.SimpleMLP
  input_dim: 384
  hidden_dim: [2048, 2048]
  output_dim: 1

regressor_optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0003
  weight_decay: 0.00001

scheduler: 
  _target_: transformers.get_linear_schedule_with_warmup
  _partial_: true
  num_warmup_steps: 1000
  num_training_steps: ${trainer.max_epochs}

compile: true

embedder_optimizer:
  _target_: torch.optim.AdamW
  _partial_: true 
  lr: 0.00002
  weight_decay: 0.00001

data_dir: ${data.data_dir}
task_names: ${data.task_names}
